name: Build multiplatform example

on:
  push:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jpackage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: natives
          path: build/jpackage

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jpackage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: natives
          path: build/jpackage

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat jpackage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: natives
          path: build/jpackage