name: Build multiplatform example

on:
  push:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jpackageImage
      - name: Test if native executable runs
        run: build/jpackage/javagi-multiplatform/bin/javagi-multiplatform

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jpackageImage
      - name: Test if native executable runs
        run: build/jpackage/javagi-multiplatform.app/Contents/MacOS/javagi-multiplatform

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat jpackageImage
      - name: Test if native executable runs
        shell: cmd
        run: build\jpackage\javagi-multiplatform\javagi-multiplatform.exe