name: Build GTK

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Upload artifacts as release'
        required: true
        type: boolean
      tag:
        description: 'The tag to clone'
        required: true

jobs:
  build:
    strategy:
      matrix:
        toolchain: [ 'mingw', 'msvc' ]
    runs-on: windows-latest

    steps:
      - name: Install GCC Dependencies
        if: ${{ matrix.toolchain == 'mingw' }}
        run: |
          choco uninstall -y mingw strawberryperl cmake.install llvm
          pip install meson ninja
      - name: Install MSVC Dependencies
        if: ${{ matrix.toolchain == 'msvc' }}
        run: |
          choco uninstall -y mingw gcc strawberryperl cmake.install llvm
          pip install meson ninja
      - name: Clone GTK tree
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          repository: 'GNOME/gtk'
          submodules: recursive
      - name: Perform Build
        run: |
          CC=${{ matrix.toolchain == 'mingw' && 'gcc' || 'msvc' }} meson setup build --prefix ${{ github.workspace }}\dist --buildtype release -Db_pie=true -Dbuild-tests=false -Dmedia-gstreamer=disabled -Dvulkan=disabled
          meson compile -C build
          meson install -C build
          cd dist\bin
          7z a ..\..\natives.zip *.dll
          7z a ..\..\executable.zip *.exe
          cd ..\..
      - name: Library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: |
            dist\bin\*.dll
      - name: Application artifact
        uses: actions/upload-artifact@v4
        with:
          name: applications
          path: |
            dist\bin\*.exe
      - name: Generate Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ inputs.release }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "libraries-${{ matrix.toolchain }}"
          prerelease: false
          title: "GTK Natives for ${{ inputs.tag }} (${{ matrix.toolchain }})"
          files: |
            natives.zip
            executable.zip