name: Build GTK

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Upload artifacts as release'
        required: true
        type: boolean
      gtktag:
        description: 'The GTK tag to clone'
        required: true
      libadwaitatag:
        description: 'The libadwaita tag to clone'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Dependencies
        run: |
          choco uninstall -y mingw strawberryperl cmake.install llvm
          pip install meson ninja
      - name: Clone GTK tree
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gtktag }}
          repository: 'GNOME/gtk'
          submodules: recursive
          path: gtk
      - name: Clone libadwaita tree
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.libadwaitatag }}
          repository: 'GNOME/libadwaita'
          submodules: recursive
          path: libadwaita
      - name: Perform Build
        run: |
          meson setup gtk\build gtk --prefix ${{ github.workspace }}\dist --buildtype release --vsenv -Db_pie=true -Dbuild-tests=false -Dmedia-gstreamer=disabled -Dvulkan=disabled
          meson compile -C gtk\build
          meson install -C gtk\build
          meson setup libadwaita\build libadwaita --prefix ${{ github.workspace }}\dist --buildtype release --vsenv -Db_pie=true
          meson compile -C libadwaita\build
          meson install -C libadwaita\build
          cd dist\bin
          7z a ..\..\natives.zip *.dll
          7z a ..\..\executable.zip *.exe
          cd ..\..
      - name: Library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: |
            dist\bin\*.dll
      - name: Application artifact
        uses: actions/upload-artifact@v4
        with:
          name: applications
          path: |
            dist\bin\*.exe
      - name: Generate Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ inputs.release }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "libraries"
          prerelease: false
          title: "GTK Natives for ${{ inputs.gtktag }}"
          files: |
            natives.zip
            executable.zip